// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'ap-southeast-1:3e18fdb8-b75c-4794-aca9-32e8f7bfc40e';
var aws_cognito_region = 'ap-southeast-1';
var aws_mandatory_sign_in = 'enable';
var aws_mobile_analytics_app_id = 'daf0ebeb0d6647028a0b530ea885d54f';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = 'a608d3a6-2f6e-49f0-a850-32902f99c53e';
var aws_project_name = 'Cloud Computing CA';
var aws_project_region = 'ap-southeast-1';
var aws_resource_name_prefix = 'cloudcomputingca-mobilehub-1876415287';
var aws_sign_in_enabled = 'enable';
var aws_user_files = 'enable';
var aws_user_files_s3_bucket = 'cloudcomputingca-userfiles-mobilehub-1876415287';
var aws_user_files_s3_bucket_region = 'ap-southeast-1';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'ap-southeast-1_HeVBMhEih';
var aws_user_pools_mfa_type = 'OFF';
var aws_user_pools_web_client_id = '7607ssp5iscuint4m1onn0qjel';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
